version: '3'

services:

  cache:
    image: redis
    container_name: redis-cache
    command: redis-server --requirepass da56038fa453c22d2c46e83179126e97d4d272d02ece83eb83a97357e842d065 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - cache-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s

  monitor:
    image: google/cadvisor
    container_name: docker-monitor
    ports:
      - 7000:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 60s

  registry:
    image: registry:2
    container_name: private-registry
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 60s

volumes:
  cache-data:
  registry-data:
